
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Toolbox APP/apps/CLion/ch-0/232.8660.139/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Toolbox APP/apps/CLion/ch-0/232.8660.139/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Toolbox APP/apps/CLion/ch-0/232.8660.139/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Toolbox APP/apps/CLion/ch-0/232.8660.139/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Toolbox APP/apps/CLion/ch-0/232.8660.139/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
